### ISSUE TITLE
Update compatibility with Turing and MonteCarloMeasurements

### ISSUE THREAD

**Issue by acwatt** [baggepinnen/Turing2MonteCarloMeasurements.jl#3]
Hello! Apologies is this is not the correct format for this request -- I'm very new to active development.

I noticed that the compatibility listings for Turing and MonteCarloMeasurements are somewhat out of date. This is limiting the usage of more recent Turing.jl functionality, and perhaps some MonteCarloMeasurements functionality as well. Specifically, I noticed that `Turing.group` is not in Turing v0.13, thus `group` cannot be used in combination with this project.

I'm wondering how much work it would take to update the compatibility in the TOML for Turing and MonteCarloMeasurements? I haven't done any testing to see what major functionality might break though. Perhaps there's an easy update that get's us closer to the latest releases of the two packages, if there's too much updating to be done to get to the latest?

Here's the status of the packages in question:
- Turing latest version is 0.24.3, the latest listed version in the TOML is 0.13.
- MonteCarloMeasurements latest version is 1.1.4, the latest listed version in the TOML is 0.9.

PS - thank you so much for creating this package! I'm using in my research on Air Pollution Policy.

**Comment by baggepinnen** [comment]
Hello and thank you for your issue! I haven't been very active in maintaining this package, I don't use Turing regularly. I suggest developing this package by calling
```
pkg> dev https://github.com/baggepinnen/Turing2MonteCarloMeasurements.jl
```
and then go to the cloned repository on your disk and update the compat listing to the latest versions, followed by running the package tests. If that works out, we could bump the compat, if it doesn't we would have to fix the issues that arose. Considering how small this package is, I suspect it would at most require a tiny amount of changes.

**Comment by acwatt** [comment]
Wonderful, thank you! I'll do that and let you know if there are any broken tests.

**Comment by baggepinnen** [comment]
I tried running the tests and there were no breakage, I pushed the updated compat bounds. I hope this works out on your end?

**Comment by acwatt** [comment]
Thank you! Yes, I have been able to upgrade my versions of Turing and MonteCarloMeasurements. There appear to be other niche issues with some of the gradient-based samplers in Turing v0.23-24 (perhaps earlier, but I haven't done a thorough check yet). These seem to only pop up for a few `truncated` distributions. If I end up needing an earlier version of Turing, like 0.21, I'll dev the package as you suggested previously, check which versions work with the truncated distributions, and run the tests on those versions.

I've decided for now to just use the `SMC` sampler instead of `NUTS`, which resolved all my issues after being able to update to Turing v0.24.3. Thank you for the bump! Should I close this issue, and just open a new issue if I decide to test other Turing versions for the compat?

**Comment by baggepinnen** [comment]
You can reopen this issue in case you run into additional compat problems with Turing.

Correctly supporting old releases of dependencies is actually somewhat of a hassle in general, it's not enough to test that the package combination works at one point in time, one should really test all supported releases of dependencies in CI to make sure that we do not introduce any incompatibilities with the old version of the dependency as we make changes to this package. For this particular package though, it's not really a problem, it does not rely much on functionality from Turing and it's not even registered, so we can introduce additional compat for Turing a few versions back if you need it.
